export const authOperationIds = [
  'authenticate',
  'refreshAccessToken',
  'logout',
  'updatePassword',
] as const

export const operationGroups = {
  patientProfile: ['findMe_1', 'updateMe_1', 'findById_1'],
  patientReports: ['create', 'findOwn'],
  patientDevices: ['findMy', 'findById_3', 'findById_4', 'getFile'],
  patientComplaints: ['create_5', 'findOwn_1', 'findById_5'],
  patientChat: ['findAllAsPatient', 'sendAsPatient', 'sendPhotoAsPatient', 'findUnreadAsPatient'],
  practitionerProfile: ['findMe', 'updateMe'],
  practitionerPatients: [
    'findMyPatients',
    'register_1',
    'changeStatus',
    'statusHistory',
    'shortReview',
    'findAll',
    'findById',
    'findAll_2',
    'findById_2',
    'findById_1',
    'getFile',
  ],
  practitionerReports: ['findAllMyPatientsReports', 'check', 'findByPatient', 'exportPdf'],
  practitionerComplaints: [
    'findAllMyPatientsComplaints',
    'review',
    'findByPatient_2',
    'exportPdf_1',
    'findById_5',
  ],
  practitionerChat: [
    'findAllAsPractitionerForPatient',
    'sendAsPractitioner',
    'sendPhotoAsPractitioner',
    'findUnreadAsPractitioner',
  ],
  practitionerDevices: [
    'findAll_3',
    'create_3',
    'findById_3',
    'create_4',
    'findByPatient_1',
    'findById_4',
  ],
  adminQualifications: ['findAll', 'create_1', 'findById'],
  adminOrganizations: ['findAll_2', 'create_2', 'findById_2'],
  adminPractitioners: ['findAll_1', 'register', 'findById_1', 'exportCsv'],
  adminDevices: ['findAll_3', 'create_3', 'findById_3'],
  adminDispenses: ['findByPatient_1', 'findById_4', 'exportCsv_1', 'shortReview', 'getFile'],
  adminProfile: [],
} as const
