/**
 * Auditable mapping from every OpenAPI operation to the user-facing product scenario.
 * Values are role/route/action identifiers, never rendered as UI copy.
 */
export const productOperationMap = {
  authenticate: 'public/login',
  refreshAccessToken: 'session/automatic-refresh',
  logout: 'all/navigation/logout',
  updatePassword: 'all/profile/change-password',
  findAllMyPatientsReports: 'practitioner/reports/queue',
  create: 'patient/reports/create',
  check: 'practitioner/reports/mark-checked',
  findOwn: 'patient/reports/history',
  findByPatient: 'practitioner/reports/patient-history',
  exportPdf: 'practitioner/reports/download-pdf',
  findAll: 'admin/qualifications/registry',
  create_1: 'admin/qualifications/create',
  findById: 'admin/qualifications/card',
  findAll_1: 'admin/practitioners/registry',
  register: 'admin/practitioners/register',
  findMe: 'practitioner/profile/view',
  updateMe: 'practitioner/profile/update',
  findById_1: 'patient/profile/practitioner-card',
  exportCsv: 'admin/practitioners/download-csv',
  findMyPatients: 'practitioner/patients/registry-and-selectors',
  register_1: 'practitioner/patients/register',
  changeStatus: 'practitioner/patients/change-status',
  findMe_1: 'patient/profile-and-dashboard/view',
  updateMe_1: 'patient/profile/update',
  statusHistory: 'practitioner/patients/status-timeline',
  exportCsv_1: 'admin/dispenses/download-patients-csv',
  findAllAsPractitionerForPatient: 'practitioner/chat/conversation',
  sendAsPractitioner: 'practitioner/chat/send-text',
  sendPhotoAsPractitioner: 'practitioner/chat/send-photo',
  findAllAsPatient: 'patient/chat/conversation',
  sendAsPatient: 'patient/chat/send-text',
  sendPhotoAsPatient: 'patient/chat/send-photo',
  findUnreadAsPractitioner: 'practitioner/chat/unread',
  findUnreadAsPatient: 'patient/chat/unread',
  findAll_2: 'admin/organizations/registry-and-selectors',
  create_2: 'admin/organizations/create',
  findById_2: 'admin/organizations/card',
  findAll_3: 'all/devices/catalog-and-selectors',
  create_3: 'practitioner-and-admin/devices/create',
  findById_3: 'all/devices/card',
  create_4: 'practitioner/devices/dispense',
  findByPatient_1: 'practitioner-and-admin/devices/patient-dispenses',
  findById_4: 'all/devices/dispense-card',
  findMy: 'patient/devices/my-dispenses',
  findAllMyPatientsComplaints: 'practitioner/complaints/queue',
  create_5: 'patient/complaints/create',
  review: 'practitioner/complaints/review',
  findByPatient_2: 'practitioner/complaints/patient-history',
  exportPdf_1: 'practitioner/complaints/download-pdf',
  findById_5: 'patient-and-practitioner/complaints/card',
  findOwn_1: 'patient/complaints/history',
  getFile: 'all/contextual-protected-images',
} as const
